import React, { Component } from "react";
import { useState } from "react";
import { Container, Row, Col, Button } from "reactstrap";
import "./Body.scss";
import { Icon } from "semantic-ui-react";
import Cards from "./Cards/Cards";
import Youtube from "../Youtube/Youtube";
import Bitcoin from "../../assets/bitcoin.png";
import bodyicon1 from "../../assets/bodyicon1.png";
import bodyicon2 from "../../assets/bodyicon2.png";
import bodyicon3 from "../../assets/bodyicon3.png";
import videohead from "../../assets/videohead.png";
import Popup from "../Popup/Popup";
import { useTranslation } from 'react-i18next';
import { Trans } from 'react-i18next';
import utils from "../../utils";

function Body(props) {
  // constructor(props) {
  //   super(props);
  //   this.state={
  //     isOpen:false,
  //   }
  //   this.togglePopup=this.togglePopup.bind(this);
  // }
  //  togglePopup(){
  //   this.state.isOpen=!this.state.isOpen;
  //   console.log(this.state.isOpen);
  // }

  function openInNewTab(url) {
    var win = window.open(url, '_blank');
    win.focus();
  }


  const [isOpen, setIsOpen] = useState(false);

  const togglePopup = () => {
    setIsOpen(!isOpen);
  };

  const { t, i18n } = useTranslation();


  return (
    <Container fluid={true} className="body-main">
      <Row className="body1">
        <Row style={{ width: "100%" }}>
          <Col lg={6} className="body-main__content">
            <h1>{t("Multiply")}</h1>
            <h2>
            <Trans >

              Your <span>Tron</span> With US
              </Trans>

            </h2>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}><Trans>Earn 200% on your deposit</Trans></p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}><Trans>Get upto 1.40% Profit every day</Trans></p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}><Trans>Stable & Real Profits generated By Forex trading</Trans></p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}>
                <Trans>No More Ponzi Contracts where most of the people end up losing their money</Trans>
              </p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}><Trans>Weekly Trading Reports for 100% transparency</Trans></p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{
                  marginTop: "7px",
                  marginLeft: "5px",
                  color: "#184fda",
                }}
              ></Icon>
              <p style={{marginLeft:"2px"}}>
              <Trans>
              Massive Binary Commissions for
               Leaders & Team builders
              </Trans>
              </p>
            </Col>
            <Button
              className="body-main__button"
              onClick={() => {
                // var refferal = document.getElementById("refferal").value;
                // this.props.invest(refferal, 1000000000);
                // togglePopup();
                window.location.href = "/stats";

              }}
            >
              <Trans>
              Participate now
              </Trans>
            </Button>
            {isOpen && (
              <Popup backGround="#4b9afb"
                content={
                  <>
                    <h2>Wallet Statistics</h2>
                    <Row className="popup-row">
                      <h3>Your Trx Wallet Address</h3>
                      <Col lg={12} xs={12}>
                        <input placeholder="adijflak45"></input>
                      </Col>
                      <Col lg={12} xs={12} className="daily-profit">
                        <Col lg={6} className="profit-input">
                          <h3>Your Current daily profit</h3>
                          <h4>0</h4>
                        </Col>
                        <Col lg={6} className="profit-data">
                          <h3>Basic Profit: 0%</h3>
                          <h3>Hold Bonus: 0%</h3>
                          <h3>Abstract Bonus: 0%</h3>
                        </Col>
                      </Col>
                      <Col lg={12} xs={12} className="user-profit">
                        <Col lg={6} className="profit-input">
                          <h3>Available Withdraw balance</h3>
                          <h4>0 TRX</h4>
                        </Col>
                        <Col lg={6} className="profit-data">
                          <h3>Request Withdraw</h3>
                          <Button
                            className="body-main__button"
                            onClick={() => {}}
                          >
                            Withdraw
                          </Button>
                        </Col>
                      </Col>
                    </Row>
                    
                  </>
                }
                handleClose={togglePopup}
              />
            )}
          </Col>
          <Col lg={6} className="body-main__bitcoin">
            {/* <img src={Bitcoin} alt="bitcoin" style={{width:"80%"}}></img> */}
          </Col>
        </Row>
      </Row>
      <Row className="body-main__footer">
        <Row className="footer-body">
          <Col lg={4} xs={12} className="footer-content hoverable" 
           onClick={()=>{
openInNewTab("https://tronscan.org/#/contract/"+utils.contractAddress)
          }}>
            <img src={bodyicon1} style={{ marginRight: "37px" }}></img>
            <p><Trans>Check Our Contract</Trans></p>
          </Col>
          <Col
            lg={4}
            xs={12}
            className="footer-content hoverable" 
            onClick={()=>{
              openInNewTab("/planEN.pdf")
                        }}
            // className="footer-content"
            style={{
              borderRight: "2px solid #39475b",
              borderLeft: "2px solid #39475b",
            }}
          >
            <img src={bodyicon2} style={{ marginRight: "10px" }}></img>
            <p><Trans>Check Our Complete Plan</Trans></p>
          </Col>
          <Col lg={4} xs={12} 
            className="footer-content hoverable" 
            onClick={()=>{
              
              var win = window.open("/weeklyreports", '');
              win.focus();  
            }}>
            <img src={bodyicon3} style={{ marginRight: "10px" }}></img>
            <p><Trans>Check Our Weekly Reports</Trans></p>
          </Col>
        </Row>
      </Row>

      <Row className="body-main__cards">
        <Cards
          card1Name={<Trans>Total Deposits</Trans>}
          card2Name={<Trans>Total Members</Trans>}
          card3Name={<Trans>Total Withdrawn</Trans>}
          card4Name={<Trans>Amount in Trading Pool</Trans>}
          card1Data={props.totalDepositAmount?props.totalDepositAmount:"-"}
          card2Data={props.totalMembers?props.totalMembers:"-"}
          card3Data={props.totalWithdraw?props.totalWithdraw:"-"}
          card4Data={props.tradingPool?props.tradingPool:"-"}
        ></Cards>
      </Row>
      <Row style={{ marginBottom: "-5%", marginTop: "-7%" }}>
        <img
          src={videohead}
          style={{
            width: "100%",
          }}
        ></img>
      </Row>
      <Row className="youtube-vid">
        <Youtube></Youtube>
      </Row>
    </Container>
  );
}
export default Body;
