import React, { Component } from "react";
import { Container, Row, Col, Button } from "reactstrap";
import "./Body.scss";
import { Icon } from "semantic-ui-react";
import Cards from './Cards/Cards';
import Youtube from '../Youtube/Youtube';
import Bitcoin from '../../assets/bitcoin.png';
import bodyicon1 from '../../assets/bodyicon1.png'
import bodyicon2 from '../../assets/bodyicon2.png'
import bodyicon3 from '../../assets/bodyicon3.png'
import videohead from '../../assets/videohead.png'
export default class Body extends Component {
  render() {
    return (
      <Container fluid={true} className="body-main">
        <Row className="body1">
        <Row style={{width:"100%"}}>
          <Col lg={6} className="body-main__content">
            <h1>Multiply</h1>
            <h2>
              Your <span>Tron</span> With US
            </h2>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{ marginTop: "7px", 
                marginLeft: "5px",
                color: "#184fda" }}
              ></Icon>
              <p>Earn 200% on your investement</p>
            </Col>
            <Col lg={12} className="body-main__list">
              <Icon
                name="check circle outline"
                style={{ marginTop: "7px",
                 marginLeft: "5px",
                 color: "#184fda"
                 }}
              ></Icon>
              <p>Get upto 1.20% profit everyday</p>
            </Col>
            <Col lg={12} className="body-main__list">
            <Icon
                name="check circle outline"
                style={{ marginTop: "7px",
                 marginLeft: "5px",
                 color: "#184fda"
                 }}
              ></Icon>
              <p>Stable and Real profit generated by Forex Trading</p>
            </Col>
            <Col lg={12} className="body-main__list">
            <Icon
                name="check circle outline"
                style={{ marginTop: "7px",
                 marginLeft: "5px",
                 color: "#184fda"
                 }}
              ></Icon>
              <p>No more ponzi contracts where most of the people end up losing there money</p>
            </Col>
            <Col lg={12} className="body-main__list">
            <Icon
                name="check circle outline"
                style={{ marginTop: "7px",
                 marginLeft: "5px",
                 color: "#184fda"
                 }}
              ></Icon>
              <p>Daily and Weekly Trading reports for 100% transparency</p>
            </Col>
            <Col lg={12} className="body-main__list">
            <Icon
                name="check circle outline"
                style={{ marginTop: "7px",
                 marginLeft: "5px",
                 color: "#184fda"
                 }}
              ></Icon>
              <p>Massive Binary Commission for leaders and Team builders daily and weekly</p>
            </Col>
            <Button className="body-main__button">Participate now</Button>
          </Col>
          <Col lg={6} className="body-main__bitcoin">
            {/* <img src={Bitcoin} alt="bitcoin" style={{width:"80%"}}></img> */}
            
          </Col>
        </Row>
      </Row>
        <Row className="body-main__footer">
          <Row className="footer-body">
            <Col lg={4} xs={12} className="footer-content">
              <img src={bodyicon1} style={{marginRight:"37px"}}></img>
              <p>Check our Contract</p>
            </Col>
            <Col lg={4} xs={12} className="footer-content" 
            style={{borderRight:"2px solid #39475b" ,borderLeft:"2px solid #39475b"}}>
            <img src={bodyicon2} style={{marginRight:"10px"}}></img>
              <p>Check our Complete Plan</p>
            </Col>
            <Col lg={4} xs={12} className="footer-content" >
            <img src={bodyicon3} style={{marginRight:"10px"}}></img>
              <p>Check our Daily Reports</p>
            </Col>
          </Row>
        </Row>
        
      
      <Row className="body-main__cards">
          <Cards 
          card1Name="Total Deposit"
          card2Name="Total Members"
          card3Name="Total Withdrawn"
          card4Name="Ammount in Trading Pool"
          card1Data="$123"
          card2Data="$123"
          card3Data="$123"
          card4Data="$123"
          ></Cards>

      </Row>
      <Row style={{marginBottom: "-5%",marginTop:"-7%"}}>
          <img src={videohead} 
          style={{ 
            width: "100%"}}></img>
      </Row>
      <Row className="youtube-vid">
        
      <Youtube></Youtube>
      </Row>
      </Container>
    );
  }
}
